[package]
name = "devefi-jes1-tcycles"
version = "0.1.0"
description = "Redeem tcycles for cycles"
repository = "https://github.com/jesssekeogh/devefi_jes1_cycles"
keywords = [ "devefi", "tcycles", "redeem" ]
license = ""

[dependencies]
base = "0.14.11"

[dev-dependencies]
devefi = "0.4.0"