[package]
name = "devefi-jes1-ntc"
version = "0.1.0"
description = "Mint NTC from ICP and Redeem NTC for cycles"
repository = "https://github.com/jesssekeogh/devefi_jes1_ntc"
keywords = [ "devefi", "ntc", "redeem", "mint" ]
license = ""

[dependencies]
base = "0.13.3"

[dev-dependencies]
devefi = "2.0.5"