[package]
name = "devefi-jes1-tcycles"
version = "0.1.0"
description = "Mint TCYCLES from ICP and Redeem TCYCLES for cycles"
repository = "https://github.com/jesssekeogh/devefi_jes1_cycles"
keywords = [ "devefi", "tcycles", "redeem", "mint" ]
license = ""

[dependencies]
base = "0.13.3"

[dev-dependencies]
devefi = "0.4.0"